server:
  port: 8081

#Database credentials
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 746233077
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      fail-on-empty-beans: false

# Displays all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"